### ISSUE TITLE
该怎么用呢

### ISSUE THREAD

**Issue by zyqq** [p-x9/pock-piano-widget#6]
该怎么导入到pock呢

**Comment by p-x9** [comment]
Hello
I added binary to [Release](https://github.com/p-x9/pock-piano-widget/releases/tag/v0.0.1).
Download the file named 'pock_piano_widget.zip', unzip it and double click it, I think it will automatically load in Pock.
https://github.com/p-x9/pock-piano-widget/releases/tag/v0.0.1

Alternatively, build with Xcode and place the binary in ~/Library/Application Support/Pock/Widgets/.
